// Code generated by protoc-gen-go. DO NOT EDIT.
// source: donaturBuku.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	donaturBuku.proto

It has these top-level messages:
	AddCustomerReq
	ReadCustomerByMobileReq
	ReadCustomerByMobileResp
	ReadCustomerResp
	UpdateCustomerReq
	ReadCustomerByEmailReq
	ReadCustomerByEmailResp
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddCustomerReq struct {
	Name          string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CustomerType  int32  `protobuf:"varint,2,opt,name=customerType" json:"customerType,omitempty"`
	Mobile        string `protobuf:"bytes,3,opt,name=mobile" json:"mobile,omitempty"`
	Email         string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Gender        string `protobuf:"bytes,5,opt,name=gender" json:"gender,omitempty"`
	CallbackPhone string `protobuf:"bytes,6,opt,name=callbackPhone" json:"callbackPhone,omitempty"`
	Status        int32  `protobuf:"varint,7,opt,name=status" json:"status,omitempty"`
}

func (m *AddCustomerReq) Reset()                    { *m = AddCustomerReq{} }
func (m *AddCustomerReq) String() string            { return proto.CompactTextString(m) }
func (*AddCustomerReq) ProtoMessage()               {}
func (*AddCustomerReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddCustomerReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddCustomerReq) GetCustomerType() int32 {
	if m != nil {
		return m.CustomerType
	}
	return 0
}

func (m *AddCustomerReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *AddCustomerReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddCustomerReq) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *AddCustomerReq) GetCallbackPhone() string {
	if m != nil {
		return m.CallbackPhone
	}
	return ""
}

func (m *AddCustomerReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ReadCustomerByMobileReq struct {
	Mobile string `protobuf:"bytes,1,opt,name=mobile" json:"mobile,omitempty"`
}

func (m *ReadCustomerByMobileReq) Reset()                    { *m = ReadCustomerByMobileReq{} }
func (m *ReadCustomerByMobileReq) String() string            { return proto.CompactTextString(m) }
func (*ReadCustomerByMobileReq) ProtoMessage()               {}
func (*ReadCustomerByMobileReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadCustomerByMobileReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type ReadCustomerByMobileResp struct {
	CustomerId    int64  `protobuf:"varint,1,opt,name=customerId" json:"customerId,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	CustomerType  int32  `protobuf:"varint,3,opt,name=customerType" json:"customerType,omitempty"`
	Mobile        string `protobuf:"bytes,4,opt,name=mobile" json:"mobile,omitempty"`
	Email         string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Gender        string `protobuf:"bytes,6,opt,name=gender" json:"gender,omitempty"`
	CallbackPhone string `protobuf:"bytes,7,opt,name=callbackPhone" json:"callbackPhone,omitempty"`
	Status        int32  `protobuf:"varint,8,opt,name=status" json:"status,omitempty"`
}

func (m *ReadCustomerByMobileResp) Reset()                    { *m = ReadCustomerByMobileResp{} }
func (m *ReadCustomerByMobileResp) String() string            { return proto.CompactTextString(m) }
func (*ReadCustomerByMobileResp) ProtoMessage()               {}
func (*ReadCustomerByMobileResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadCustomerByMobileResp) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *ReadCustomerByMobileResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadCustomerByMobileResp) GetCustomerType() int32 {
	if m != nil {
		return m.CustomerType
	}
	return 0
}

func (m *ReadCustomerByMobileResp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ReadCustomerByMobileResp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ReadCustomerByMobileResp) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *ReadCustomerByMobileResp) GetCallbackPhone() string {
	if m != nil {
		return m.CallbackPhone
	}
	return ""
}

func (m *ReadCustomerByMobileResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ReadCustomerResp struct {
	AllCustomer []*ReadCustomerByMobileResp `protobuf:"bytes,1,rep,name=allCustomer" json:"allCustomer,omitempty"`
}

func (m *ReadCustomerResp) Reset()                    { *m = ReadCustomerResp{} }
func (m *ReadCustomerResp) String() string            { return proto.CompactTextString(m) }
func (*ReadCustomerResp) ProtoMessage()               {}
func (*ReadCustomerResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadCustomerResp) GetAllCustomer() []*ReadCustomerByMobileResp {
	if m != nil {
		return m.AllCustomer
	}
	return nil
}

type UpdateCustomerReq struct {
	CustomerId    int64  `protobuf:"varint,1,opt,name=customerId" json:"customerId,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	CustomerType  int32  `protobuf:"varint,3,opt,name=customerType" json:"customerType,omitempty"`
	Mobile        string `protobuf:"bytes,4,opt,name=mobile" json:"mobile,omitempty"`
	Email         string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Gender        string `protobuf:"bytes,6,opt,name=gender" json:"gender,omitempty"`
	CallbackPhone string `protobuf:"bytes,7,opt,name=callbackPhone" json:"callbackPhone,omitempty"`
	Status        int32  `protobuf:"varint,8,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateCustomerReq) Reset()                    { *m = UpdateCustomerReq{} }
func (m *UpdateCustomerReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateCustomerReq) ProtoMessage()               {}
func (*UpdateCustomerReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateCustomerReq) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *UpdateCustomerReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCustomerReq) GetCustomerType() int32 {
	if m != nil {
		return m.CustomerType
	}
	return 0
}

func (m *UpdateCustomerReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UpdateCustomerReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateCustomerReq) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UpdateCustomerReq) GetCallbackPhone() string {
	if m != nil {
		return m.CallbackPhone
	}
	return ""
}

func (m *UpdateCustomerReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ReadCustomerByEmailReq struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *ReadCustomerByEmailReq) Reset()                    { *m = ReadCustomerByEmailReq{} }
func (m *ReadCustomerByEmailReq) String() string            { return proto.CompactTextString(m) }
func (*ReadCustomerByEmailReq) ProtoMessage()               {}
func (*ReadCustomerByEmailReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadCustomerByEmailReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ReadCustomerByEmailResp struct {
	CustomerId    int64  `protobuf:"varint,1,opt,name=customerId" json:"customerId,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	CustomerType  int32  `protobuf:"varint,3,opt,name=customerType" json:"customerType,omitempty"`
	Mobile        string `protobuf:"bytes,4,opt,name=mobile" json:"mobile,omitempty"`
	Email         string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Gender        string `protobuf:"bytes,6,opt,name=gender" json:"gender,omitempty"`
	CallbackPhone string `protobuf:"bytes,7,opt,name=callbackPhone" json:"callbackPhone,omitempty"`
	Status        int32  `protobuf:"varint,8,opt,name=status" json:"status,omitempty"`
}

func (m *ReadCustomerByEmailResp) Reset()                    { *m = ReadCustomerByEmailResp{} }
func (m *ReadCustomerByEmailResp) String() string            { return proto.CompactTextString(m) }
func (*ReadCustomerByEmailResp) ProtoMessage()               {}
func (*ReadCustomerByEmailResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReadCustomerByEmailResp) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *ReadCustomerByEmailResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadCustomerByEmailResp) GetCustomerType() int32 {
	if m != nil {
		return m.CustomerType
	}
	return 0
}

func (m *ReadCustomerByEmailResp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *ReadCustomerByEmailResp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ReadCustomerByEmailResp) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *ReadCustomerByEmailResp) GetCallbackPhone() string {
	if m != nil {
		return m.CallbackPhone
	}
	return ""
}

func (m *ReadCustomerByEmailResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*AddCustomerReq)(nil), "grpc.AddCustomerReq")
	proto.RegisterType((*ReadCustomerByMobileReq)(nil), "grpc.ReadCustomerByMobileReq")
	proto.RegisterType((*ReadCustomerByMobileResp)(nil), "grpc.ReadCustomerByMobileResp")
	proto.RegisterType((*ReadCustomerResp)(nil), "grpc.ReadCustomerResp")
	proto.RegisterType((*UpdateCustomerReq)(nil), "grpc.UpdateCustomerReq")
	proto.RegisterType((*ReadCustomerByEmailReq)(nil), "grpc.ReadCustomerByEmailReq")
	proto.RegisterType((*ReadCustomerByEmailResp)(nil), "grpc.ReadCustomerByEmailResp")
}

func init() { proto.RegisterFile("donaturBuku.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x54, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0xad, 0x9b, 0x4d, 0x0a, 0xb3, 0xa5, 0xd0, 0x61, 0xb5, 0xb5, 0x02, 0xad, 0x56, 0x16, 0x87,
	0x3d, 0xa5, 0xa2, 0x9c, 0x91, 0x4a, 0xab, 0x1e, 0x38, 0x20, 0xa1, 0xb0, 0x88, 0xb3, 0x93, 0x98,
	0xb0, 0x6a, 0x12, 0xa7, 0xf9, 0x40, 0xda, 0x3f, 0xc0, 0xaf, 0xe3, 0xbf, 0x70, 0x82, 0x33, 0xb2,
	0x93, 0x2c, 0x4e, 0x49, 0xd3, 0x7b, 0x6f, 0x99, 0xf1, 0xbc, 0xf8, 0xbd, 0xa7, 0xe7, 0x81, 0xc3,
	0x48, 0x66, 0xbc, 0xaa, 0x8b, 0x8b, 0xfa, 0xba, 0xf6, 0xf2, 0x42, 0x56, 0x12, 0x27, 0x71, 0x91,
	0x87, 0xee, 0x8b, 0x58, 0xca, 0x38, 0x11, 0xa7, 0xba, 0x17, 0xd4, 0x5f, 0x4f, 0x45, 0x9a, 0x57,
	0x9b, 0x66, 0x84, 0xfd, 0x24, 0x70, 0xf0, 0x2e, 0x8a, 0x2e, 0xeb, 0xb2, 0x92, 0xa9, 0x28, 0x7c,
	0x71, 0x83, 0x08, 0x93, 0x8c, 0xa7, 0x82, 0x92, 0x05, 0x59, 0x3e, 0xf6, 0xf5, 0x37, 0x32, 0xd8,
	0x0f, 0xdb, 0x91, 0xd5, 0x26, 0x17, 0x74, 0x77, 0x41, 0x96, 0xb6, 0xdf, 0xeb, 0xe1, 0x1c, 0x9c,
	0x54, 0x06, 0xeb, 0x44, 0x50, 0x4b, 0x23, 0xdb, 0x0a, 0x67, 0x60, 0x8b, 0x94, 0xaf, 0x13, 0x3a,
	0xd1, 0xed, 0xa6, 0x50, 0xd3, 0xb1, 0xc8, 0x22, 0x51, 0x50, 0xbb, 0x99, 0x6e, 0x2a, 0x7c, 0x05,
	0x4f, 0x42, 0x9e, 0x24, 0x01, 0x0f, 0xaf, 0x3f, 0x7e, 0x93, 0x99, 0xa0, 0x8e, 0x3e, 0xee, 0x37,
	0x15, 0xba, 0xac, 0x78, 0x55, 0x97, 0x74, 0x4f, 0x33, 0x69, 0x2b, 0xf6, 0x1a, 0x8e, 0x7c, 0xc1,
	0xb7, 0x72, 0x2e, 0x36, 0x1f, 0x34, 0x07, 0x25, 0xeb, 0x1f, 0x3d, 0x62, 0xd2, 0x63, 0x7f, 0x08,
	0xd0, 0x61, 0x4c, 0x99, 0xe3, 0x09, 0x40, 0xa7, 0xf1, 0x7d, 0xa4, 0x81, 0x96, 0x6f, 0x74, 0xb6,
	0x5e, 0xed, 0x8e, 0x78, 0x65, 0x8d, 0x7a, 0x35, 0x19, 0xf6, 0xca, 0x1e, 0xf6, 0xca, 0x19, 0xf7,
	0x6a, 0x6f, 0xdc, 0xab, 0x47, 0x3d, 0xaf, 0x56, 0xf0, 0xcc, 0xd4, 0xad, 0xf5, 0x9e, 0xc3, 0x94,
	0x27, 0x49, 0xd7, 0xa2, 0x64, 0x61, 0x2d, 0xa7, 0x67, 0x27, 0x9e, 0xca, 0x91, 0x77, 0x97, 0x49,
	0xbe, 0x09, 0x61, 0xbf, 0x08, 0x1c, 0x7e, 0xce, 0x23, 0x5e, 0x09, 0x33, 0x53, 0x0f, 0xd9, 0x47,
	0x0f, 0xe6, 0x7d, 0x6b, 0xae, 0xd4, 0x65, 0x4a, 0xf5, 0x96, 0x05, 0x31, 0x58, 0xb0, 0xdf, 0xe4,
	0x76, 0x48, 0x5b, 0xc0, 0xc3, 0xce, 0xdb, 0xd9, 0x0f, 0x0b, 0x9e, 0x76, 0x9a, 0x3f, 0x89, 0xe2,
	0xfb, 0x3a, 0x14, 0xf8, 0x16, 0xa6, 0xc6, 0xf6, 0xc1, 0x59, 0x93, 0xb4, 0xfe, 0x42, 0x72, 0xe7,
	0x5e, 0xb3, 0xc1, 0xbc, 0x6e, 0x83, 0x79, 0x57, 0x6a, 0x83, 0xb1, 0x1d, 0xfc, 0x02, 0xb3, 0xa1,
	0x54, 0xe2, 0xf1, 0x58, 0x62, 0x6f, 0xdc, 0x7b, 0x02, 0xcd, 0x76, 0xf0, 0x1c, 0xf6, 0xcd, 0x53,
	0xbc, 0x83, 0x82, 0xa2, 0x76, 0xfb, 0x4f, 0xed, 0x1f, 0x2e, 0xe1, 0xa0, 0xff, 0x0c, 0xf0, 0xa8,
	0x99, 0xfd, 0xef, 0x71, 0x8c, 0xe8, 0x5b, 0xc1, 0xf3, 0x81, 0xa4, 0xe0, 0xcb, 0x21, 0xfe, 0x5d,
	0xea, 0xdc, 0xe3, 0x91, 0x53, 0x45, 0x2d, 0x70, 0xf4, 0x3d, 0x6f, 0xfe, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xba, 0xa9, 0x94, 0x63, 0x32, 0x06, 0x00, 0x00,
}
